import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="mb-5 p-4">
          <nav className="flex gap-5 border black border-solid p-5">
            <Link href={"/"}>Home</Link>

            <Link href={"/products"}>products</Link>

            <Link href={"/dashboard"}>Dashboard</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
